use_frameworks!

platform :ios, '13.0'

target 'EncryptingSwift_Example' do
  pod 'EncryptingSwift', :path => '../'
  pod 'ed25519swift', '~> 1.2.8'
  pod 'Sr25519', '~> 0.1.3'
  pod 'CommonSwift', :git => 'https://github.com/sublabdev/common-swift.git', :branch => 'dev'

  target 'EncryptingSwift_Tests' do
    inherit! :search_paths

    
  end
end
