use_frameworks!

platform :ios, '13.0'

target 'EncryptingSwift_Example' do
  pod 'EncryptingSwift', :path => '../'
  pod 'ed25519swift'
  pod 'Sr25519'
  pod 'CommonSwift', :git => 'https://github.com/sublabdev/common-swift.git', :commit => '5bdbe0884ebbdaa8bec9b2f73133764c489d180f'

  target 'EncryptingSwift_Tests' do
    inherit! :search_paths

    
  end
end
